import type { CompanyFundamentals } from './types';

/**
 * Manually curated fundamentals snapshot.
 *
 * Figures are approximate and rounded, transcribed from each company's FY2024
 * annual filing (10-K or equivalent); revenueFiveYearsAgo is the FY2019
 * (or first comparable fiscal year) figure used for the 5y CAGR. This is a
 * static research dataset, not a live feed, and is deliberately limited to
 * price-independent fundamentals so every derived number on the page is
 * reproducible from the filing inputs shown here.
 */
export const SNAPSHOT_AS_OF = 'FY2024 annual filings, curated 2026-07';

export const UNIVERSE: CompanyFundamentals[] = [
  {
    ticker: 'AAPL',
    name: 'Apple Inc.',
    currency: 'USD',
    fiscalYearEnd: 'Sep 2024',
    revenue: 391.0,
    revenueFiveYearsAgo: 260.2,
    netIncome: 93.7,
    ebit: 123.2,
    grossMarginPct: 46.2,
    shareholderEquity: 56.9,
    totalDebt: 106.6,
    operatingCashFlow: 118.3,
    capex: 9.4,
    eps: 6.08,
    bookValuePerShare: 3.77,
    moat: 'Wide',
  },
  {
    ticker: 'MSFT',
    name: 'Microsoft',
    currency: 'USD',
    fiscalYearEnd: 'Jun 2024',
    revenue: 245.1,
    revenueFiveYearsAgo: 125.8,
    netIncome: 88.1,
    ebit: 109.4,
    grossMarginPct: 69.8,
    shareholderEquity: 268.5,
    totalDebt: 67.1,
    operatingCashFlow: 118.5,
    capex: 44.5,
    eps: 11.8,
    bookValuePerShare: 36.11,
    moat: 'Wide',
  },
  {
    ticker: 'GOOGL',
    name: 'Alphabet',
    currency: 'USD',
    fiscalYearEnd: 'Dec 2024',
    revenue: 350.0,
    revenueFiveYearsAgo: 161.9,
    netIncome: 100.1,
    ebit: 112.4,
    grossMarginPct: 58.2,
    shareholderEquity: 325.1,
    totalDebt: 28.1,
    operatingCashFlow: 125.3,
    capex: 52.5,
    eps: 8.04,
    bookValuePerShare: 26.5,
    moat: 'Wide',
  },
  {
    ticker: 'NVDA',
    name: 'NVIDIA',
    currency: 'USD',
    fiscalYearEnd: 'Jan 2025',
    revenue: 130.5,
    revenueFiveYearsAgo: 10.9,
    netIncome: 72.9,
    ebit: 81.5,
    grossMarginPct: 75.0,
    shareholderEquity: 79.3,
    totalDebt: 8.5,
    operatingCashFlow: 64.1,
    capex: 3.2,
    eps: 2.94,
    bookValuePerShare: 3.24,
    moat: 'Wide',
  },
  {
    ticker: 'META',
    name: 'Meta Platforms',
    currency: 'USD',
    fiscalYearEnd: 'Dec 2024',
    revenue: 164.5,
    revenueFiveYearsAgo: 70.7,
    netIncome: 62.4,
    ebit: 69.4,
    grossMarginPct: 81.7,
    shareholderEquity: 182.7,
    totalDebt: 28.8,
    operatingCashFlow: 91.3,
    capex: 37.3,
    eps: 23.86,
    bookValuePerShare: 72.3,
    moat: 'Wide',
  },
  {
    ticker: 'ASML',
    name: 'ASML Holding',
    currency: 'EUR',
    fiscalYearEnd: 'Dec 2024',
    revenue: 28.3,
    revenueFiveYearsAgo: 11.8,
    netIncome: 7.6,
    ebit: 9.1,
    grossMarginPct: 51.3,
    shareholderEquity: 18.5,
    totalDebt: 4.6,
    operatingCashFlow: 11.2,
    capex: 2.0,
    eps: 19.25,
    bookValuePerShare: 47.0,
    moat: 'Wide',
  },
  {
    ticker: 'V',
    name: 'Visa Inc.',
    currency: 'USD',
    fiscalYearEnd: 'Sep 2024',
    revenue: 35.9,
    revenueFiveYearsAgo: 23.0,
    netIncome: 19.7,
    ebit: 23.6,
    grossMarginPct: 80.0,
    shareholderEquity: 39.1,
    totalDebt: 20.8,
    operatingCashFlow: 19.9,
    capex: 1.3,
    eps: 9.73,
    bookValuePerShare: 19.4,
    moat: 'Wide',
  },
  {
    ticker: 'ADBE',
    name: 'Adobe Inc.',
    currency: 'USD',
    fiscalYearEnd: 'Nov 2024',
    revenue: 21.5,
    revenueFiveYearsAgo: 11.2,
    netIncome: 5.6,
    ebit: 6.7,
    grossMarginPct: 89.0,
    shareholderEquity: 14.1,
    totalDebt: 5.6,
    operatingCashFlow: 8.1,
    capex: 0.2,
    eps: 12.36,
    bookValuePerShare: 31.9,
    moat: 'Wide',
  },
  {
    ticker: 'ORCL',
    name: 'Oracle',
    currency: 'USD',
    fiscalYearEnd: 'May 2024',
    revenue: 53.0,
    revenueFiveYearsAgo: 39.5,
    netIncome: 10.5,
    ebit: 15.4,
    grossMarginPct: 71.4,
    shareholderEquity: 8.7,
    totalDebt: 84.5,
    operatingCashFlow: 18.7,
    capex: 6.9,
    eps: 3.71,
    bookValuePerShare: 3.15,
    moat: 'Narrow',
  },
  {
    ticker: 'INFY',
    name: 'Infosys',
    currency: 'USD',
    fiscalYearEnd: 'Mar 2024',
    revenue: 18.6,
    revenueFiveYearsAgo: 11.8,
    netIncome: 3.2,
    ebit: 3.9,
    grossMarginPct: 29.7,
    shareholderEquity: 10.6,
    totalDebt: 0.1,
    operatingCashFlow: 3.0,
    capex: 0.3,
    eps: 0.77,
    bookValuePerShare: 2.56,
    moat: 'Narrow',
  },
];
